opt_in_rules:
  - all

disabled_rules:
  - prefer_nimble
  - anyobject_protocol
  - inert_defer
  - unused_capture_list
  - missing_docs
  - explicit_acl
  - explicit_top_level_acl
  - required_deinit
  - explicit_type_interface
  - explicit_enum_raw_value
  - sorted_enum_cases
  - extension_access_modifier
  - file_name
  - no_grouping_extension


included:
  - Sources

line_length: 170

identifier_name:
  excluded:
    - Current
