name: Build and Test

on:
  push:
    branches: [ main ]
    paths:
      - 'Sources/**.swift'
      - 'Tests/**.swift'
      - 'Package.swift'
      - 'Package.resolved'
      - '.github/workflows/build.yml'
  pull_request:
    paths: 
      - 'Sources/**.swift'
      - 'Tests/**.swift'
      - 'Package.swift'
      - 'Package.resolved'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache .build 
      uses: actions/cache@v4.0.2
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - name: Build
      run: swift build --build-tests --verbose
    - name: Run tests
      run: swift test --verbose --enable-code-coverage --parallel | xcpretty
    - name: Generate coverage
      run: ./.scripts/generate_coverage.sh
    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        files: info.lcov
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: info.lcov
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true