name: Build and Test

on:
  push:
    branches: [ main ]
    paths:
      - 'Sources/**.swift'
      - 'Tests/**.swift'
      - 'Package.swift'
      - '.github/workflows/build.yml'
  pull_request:
    paths: 
      - 'Sources/**.swift'
      - 'Tests/**.swift'
      - 'Package.swift'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache .build 
      uses: actions/cache@v2.1.2
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - name: Build
      run: swift build --build-tests --verbose
    - name: Run tests
      run: swift test --verbose --enable-code-coverage --parallel | xcpretty
    - name: Generate coverage
      run: ./.scripts/cov.sh