name: Build and Test

on:
  push:
    branches: [ main ]
    paths:
      - 'Sources/**.swift'
      - 'Tests/**.swift'
      - 'Package.swift'
      - 'Package.resolved'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'Sources/**.swift'
      - 'Tests/**.swift'
      - 'Package.swift'
      - 'Package.resolved'
      - '.github/workflows/build.yml'

concurrency:
  group: test_${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_with_spm:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.3.app
    - name: Cache .build
      uses: actions/cache@v4.2.3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - name: Build with Swift Package Manager
      run: swift build --verbose
    - name: Run tests
      run: swift test --verbose --enable-swift-testing --enable-code-coverage --xunit-output result.xml
      continue-on-error: true
    - name: Upload test results to Codecov
      uses: codecov/test-results-action@v1
      with:
        files: result-swift-testing.xml
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Generate coverage
      run: ./.scripts/generate_coverage.sh
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: info.lcov
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
  build_with_xcode:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.3.app
    - name: Cache .build
      uses: actions/cache@v4.2.3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - name: Build with Xcode
      run: xcodebuild -scheme Bump -sdk macosx -destination 'platform=macOS' build
    - name: Run tests
      run: set -o pipefail && xcodebuild -scheme Bump -sdk macosx -destination 'platform=macOS' test | xcbeautify --renderer github-actions
  linux:
    runs-on: ubuntu-latest
    container: swift:6.1
    steps:
        - uses: actions/checkout@v4
        # - name: Cache .build
        #   uses: actions/cache@v4.2.3
        #   with:
        #     path: ./.build
        #     key: ${{ runner.os }}-spm-${{ hashFiles('./**/Package.resolved') }}
        #     restore-keys: |
        #       ${{ runner.os }}-spm-
        - name: Run tests
          run: swift test --enable-swift-testing
