name: Lint

on:
  push:
    branches: [ main ]
    paths:
      - 'Sources/**.swift'
      - '.github/workflows/lint.yml'
  pull_request:
    paths: 
      - 'Sources/**.swift'
      - '.github/workflows/lint.yml'

jobs:
  lint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Swiftlint
      run: swiftlint --strict --reporter github-actions-logging