name: Lint

on:
  push:
    branches: [ main ]
    paths:
      - 'Sources/**.swift'
      - 'Tests/**.swift'
      - 'Package.swift'
      - 'Package.resolved'
  pull_request:
    paths: 
      - 'Sources/**.swift'
      - 'Tests/**.swift'
      - 'Package.swift'
      - 'Package.resolved'

concurrency:
  group: lint_${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install SwiftLint
      run: brew install swiftlint
    - name: Run Swiftlint
      run: swiftlint . --strict --reporter github-actions-logging