name: Lint

on:
  push:
    branches: [ main ]
    paths:
      - 'Sources/**.swift'
      - 'Tests/**.swift'
      - 'Package.swift'
      - 'Package.resolved'
      - '.github/workflows/build.yml'
  pull_request:
    paths: 
      - 'Sources/**.swift'
      - 'Tests/**.swift'
      - 'Package.swift'
      - 'Package.resolved'
      - '.github/workflows/build.yml'

jobs:
  lint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Swiftlint
      run: swift package plugin swiftlint --strict --reporter github-actions-logging