name: Swift

on:
  push:
    branches: [ master ]
    paths:
      - 'Sources/**.swift'
      - 'Tests/**.swift'
      - 'Package.swift'
      - '.github/workflows/swift.yml'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache .build 
      uses: actions/cache@v2.1.2
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --enable-code-coverage --parallel
    - name: Generate coverage
      run: ./.scripts/cov.sh
